# Guided Capstone Step 4. Pre-Processing and Training Data Development

**The Data Science Method**  


1.   Problem Identification 


2.   Data Wrangling 
  
 
3.   Exploratory Data Analysis   

4.   **Pre-processing and Training Data Development**  
 * Create dummy or indicator features for categorical variables
  * Standardize the magnitude of numeric features
  * Split into testing and training datasets
  * Apply scaler to the testing set
5.   Modeling 
  * Fit Models with Training Data Set
  * Review Model Outcomes — Iterate over additional models as needed.
  * Identify the Final Model

6.   Documentation
  * Review the Results
  * Present and share your findings - storytelling
  * Finalize Code 
  * Finalize Documentation

**<font color='teal'> Start by loading the necessary packages as we did in step 3 and printing out our current working directory just to confirm we are in the correct project directory. </font>**

In [1]:
#load python packages
import os
import pandas as pd
import datetime
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline

print(os.getcwd())

/Users/josevans

**<font color='teal'>  Load the csv file you created in step 3, remember it should be saved inside your data subfolder and print the first five rows.</font>**

In [4]:
os.chdir('/Users/josevans/Desktop/Springboard')
os.listdir()
df = pd.read_csv('step3_output.csv').drop('Unnamed: 0', axis=1)
df.head()

,Name,state,summit_elev,vertical_drop,trams,fastEight,fastSixes,fastQuads,quad,triple,...,SkiableTerrain_ac,Snow Making_ac,daysOpenLastYear,yearsOpen,averageSnowfall,AdultWeekday,AdultWeekend,projectedDaysOpen,NightSkiing_ac,clusters
0,Hilltop Ski Area,Alaska,2090,294,0,0.0,0,0,0,1,...,30.0,30.000000,150.0,36.0,69.0,30.0,34.000000,152.0,30.0,0
1,Sunrise Park Resort,Arizona,11100,1800,0,0.0,0,1,2,3,...,800.0,80.000000,115.0,49.0,250.0,74.0,78.000000,104.0,80.0,1
2,Yosemite Ski & Snowboard Area,California,7800,600,0,0.0,0,0,0,1,...,88.0,206.640693,110.0,84.0,300.0,47.0,47.000000,107.0,0.0,1
3,Boreal Mountain Resort,California,7700,500,0,0.0,0,1,1,3,...,380.0,200.000000,150.0,54.0,400.0,49.0,64.226929,150.0,200.0,1
4,Dodge Ridge,California,8200,1600,0,0.0,0,0,1,2,...,862.0,273.203125,140.0,69.0,350.0,78.0,78.000000,140.0,0.0,1

## Create dummy features for categorical variables

**<font color='teal'> Create dummy variables for `state`. Add the dummies back to the dataframe and remove the original column for `state`. </font>**

Hint: you can see an example of how to execute this in Aiden's article on preprocessing [here](https://medium.com/@aiden.dataminer/the-data-science-method-dsm-pre-processing-and-training-data-development-fd2d75182967).

In [5]:
dfo = pd.get_dummies(df['state'])
df = pd.concat([df.drop(['state'], axis=1), dfo], axis=1)
df.head().T

,0,1,2,3,4
Name,Hilltop Ski Area,Sunrise Park Resort,Yosemite Ski & Snowboard Area,Boreal Mountain Resort,Dodge Ridge
summit_elev,2090,11100,7800,7700,8200
vertical_drop,294,1800,600,500,1600
trams,0,0,0,0,0
fastEight,0,0,0,0,0
fastSixes,0,0,0,0,0
fastQuads,0,1,0,1,0
quad,0,2,0,1,1
triple,1,3,1,3,2
double,0,1,3,1,5
surface,2,0,1,2,4
total_chairs,3,7,5,8,12
Runs,13,65,10,33,67
TerrainParks,1,2,2,6,5
LongestRun_mi,1,1.2,0.4,1,2
SkiableTerrain_ac,30,800,88,380,862
Snow Making_ac,30,80,206.641,200,273.203
daysOpenLastYear,150,115,110,150,140
yearsOpen,36,49,84,54,69
averageSnowfall,69,250,300,400,350
AdultWeekday,30,74,47,49,78
AdultWeekend,34,78,47,64.2269,78
projectedDaysOpen,152,104,107,150,140
NightSkiing_ac,30,80,0,200,0
clusters,0,1,1,1,1
Alaska,1,0,0,0,0
Arizona,0,1,0,0,0
California,0,0,1,1,1
Colorado,0,0,0,0,0
Connecticut,0,0,0,0,0
Idaho,0,0,0,0,0
Illinois,0,0,0,0,0
Indiana,0,0,0,0,0
Iowa,0,0,0,0,0
Maine,0,0,0,0,0
Maryland,0,0,0,0,0
Massachusetts,0,0,0,0,0
Michigan,0,0,0,0,0
Minnesota,0,0,0,0,0
Missouri,0,0,0,0,0
Montana,0,0,0,0,0
Nevada,0,0,0,0,0
New Hampshire,0,0,0,0,0
New Jersey,0,0,0,0,0
New Mexico,0,0,0,0,0
New York,0,0,0,0,0
North Carolina,0,0,0,0,0
Ohio,0,0,0,0,0
Oregon,0,0,0,0,0
Pennsylvania,0,0,0,0,0
Rhode Island,0,0,0,0,0
South Dakota,0,0,0,0,0
Tennessee,0,0,0,0,0
Utah,0,0,0,0,0
Vermont,0,0,0,0,0
Virginia,0,0,0,0,0
Washington,0,0,0,0,0
West Virginia,0,0,0,0,0
Wisconsin,0,0,0,0,0
Wyoming,0,0,0,0,0

## Standardize the magnitude of numeric features

**<font color='teal'> Using sklearn preprocessing standardize the scale of the features of the dataframe except the name of the resort which we done't need in the dataframe for modeling, so it can be droppped here as well. Also, we want to hold out our response variable(s) so we can have their true values available for model performance review. Let's set `AdultWeekend` to the y variable as our response for scaling and modeling. Later we will go back and consider the `AdultWeekday`, `dayOpenLastYear`, and `projectedDaysOpen`. For now leave them in the development dataframe. </font>**

In [50]:
# first we import the preprocessing package from the sklearn library
from sklearn.preprocessing import StandardScaler

# Declare an explanatory variable, called X,and assign it the result of dropping 'Name' and 'AdultWeekend' from the df
X = df.drop(['Name','AdultWeekend'], axis=1)

print(X)

# Declare a response variable, called y, and assign it the AdultWeekend column of the df 
y = df.AdultWeekend 

# Here we use the StandardScaler() method of the preprocessing package, and then call the fit() method with parameter X 
scaler = StandardScaler()

scaler.fit(X)

# Declare a variable called X_scaled, and assign it the result of calling the transform() method with parameter X 
X_scaled=scaler.transform(X)

     summit_elev  vertical_drop  trams  fastEight  fastSixes  fastQuads  quad  \
0           2090            294      0        0.0          0          0     0
1          11100           1800      0        0.0          0          1     2
2           7800            600      0        0.0          0          0     0
3           7700            500      0        0.0          0          1     1
4           8200           1600      0        0.0          0          0     1
..           ...            ...    ...        ...        ...        ...   ...
170         7428            810      0        0.0          0          0     0
171         7808           1571      0        0.0          0          0     1
172         9663            990      0        0.0          0          0     0
173         9500           1100      0        0.0          0          0     0
174         6817           2353      0        0.0          0          3     2

     triple  double  surface  ...  Rhode Island  South Dakota  Tennessee  \
0         1       0        2  ...             0             0          0
1         3       1        0  ...             0             0          0
2         1       3        1  ...             0             0          0
3         3       1        2  ...             0             0          0
4         2       5        4  ...             0             0          0
..      ...     ...      ...  ...           ...           ...        ...
170       1       1        1  ...             0             0          0
171       1       1        0  ...             0             0          0
172       1       3        1  ...             0             0          0
173       2       0        0  ...             0             0          0
174       6       0        3  ...             0             0          0

     Utah  Vermont  Virginia  Washington  West Virginia  Wisconsin  Wyoming
0       0        0         0           0              0          0        0
1       0        0         0           0              0          0        0
2       0        0         0           0              0          0        0
3       0        0         0           0              0          0        0
4       0        0         0           0              0          0        0
..    ...      ...       ...         ...            ...        ...      ...
170     0        0         0           0              0          0        1
171     0        0         0           0              0          0        1
172     0        0         0           0              0          0        1
173     0        0         0           0              0          0        1
174     0        0         0           0              0          0        0

[175 rows x 58 columns]

In [51]:
X_scaled

array([[-0.49058518, -0.93682899,  0.        , ..., -0.13206764,
        -0.25898489, -0.17149859],
       [ 2.3064562 ,  1.59103243,  0.        , ..., -0.13206764,
        -0.25898489, -0.17149859],
       [ 1.28201263, -0.42319978,  0.        , ..., -0.13206764,
        -0.25898489, -0.17149859],
       ...,
       [ 1.86035759,  0.23142569,  0.        , ..., -0.13206764,
        -0.25898489,  5.83095189],
       [ 1.80975629,  0.41606364,  0.        , ..., -0.13206764,
        -0.25898489,  5.83095189],
       [ 0.97685262,  2.51925778,  0.        , ..., -0.13206764,
        -0.25898489, -0.17149859]])

## Split into training and testing datasets

**<font color='teal'> Using sklearn model selection import train_test_split, and create a 75/25 split with the y = `AdultWeekend`. We will start by using the adult weekend ticket price as our response variable for modeling.</font>**

In [52]:
# Import the train_test_split function from the sklearn.model_selection utility.  
from sklearn.model_selection import train_test_split

# Get the 1-dimensional flattened array of our response variable y by calling the ravel() function on y
y = y.ravel()

# Call the train_test_split() function with the first two parameters set to X_scaled and y 
# Declare four variables, X_train, X_test, y_train and y_test separated by commas 
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.25, random_state=35)

Here we start the actual modeling work. First let's fit a multiple linear regression model to predict the `AdultWeekend` price.

# Guided Capstone Step 5. Modeling

This is the fifth step in the Data Science Method. In the previous steps you cleaned and prepared the datasets. Now it's time to get into the most exciting part: modeling! In this exercise, you'll build three different models and compare each model's performance. In the end, you'll choose the best model for demonstrating insights to Big Mountain management.



### **The Data Science Method**  


1.   Problem Identification 

2.   Data Wrangling 
  
3.   Exploratory Data Analysis 
 
4.   Pre-processing and Training Data Development

5.   **Modeling**
  * Fit Models with Training Data Set
  * Review Model Outcomes — Iterate over additional models as needed.
  * Identify the Final Model

6.   Documentation
  * Review the Results
  * Present and share your findings - storytelling
  * Finalize Code 
  * Finalize Documentation

## Fit Models with a Training Dataset

**<font color='teal'> Using sklearn, fit the model on your training dataset.</font>**

#### Model 1

In [53]:
#all first model set
from sklearn import linear_model
from sklearn.metrics import explained_variance_score,mean_absolute_error
lm = linear_model.LinearRegression()
model = lm.fit(X_train,y_train)

**<font color='teal'> Predict on the testing dataset and score the model performance with the y_test set and the y-pred values. The explained variance is a measure of the variation explained by the model. This is also known as the R-squared value. </font>**

Hint: you will have to use the `predict()` method here as it's used in this [DSM article](https://medium.com/@aiden.dataminer/the-data-science-method-dsm-modeling-56b4233cad1b) about modeling.

In [56]:
# Make a variable called y_pred and assign it the result of calling predict() on our model variable with parameter X_test
y_pred = lm.predict(X_test)

## Review Model Outcomes — Iterate over additional models as needed

In [57]:
# You might want to use the explained_variance_score() and mean_absolute_error() metrics.
# To do so, you will need to import them from sklearn.metrics. 
# You can plug y_test and y_pred into the functions to evaluate the model

mae = mean_absolute_error(y_test, y_pred)
evs = explained_variance_score(y_test, y_pred)

print(mae, evs)

225794808609.25305 -2.7515340743750435e+21

In [73]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(random_state=300, n_estimators=200)
regressor.fit(X_train, y_train)
regressor.score(X_test, y_test)


y_pred = regressor.predict(X_test)
from sklearn.metrics import mean_squared_error
from math import sqrt
rmse = sqrt(mean_squared_error(y_test, y_pred))
rmse

8.407740635167443

In [67]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import GridSearchCV
param_grid = {"n_estimators": [1000],
 "max_depth": [None],
 "max_features": [18, 20, 22, 24],
 "min_samples_split": [2],
 "min_samples_leaf": [1],
 "bootstrap": [False]}
model = RandomForestRegressor(random_state=600)
grid = GridSearchCV(estimator=model, param_grid=param_grid, n_jobs=-1)
grid.fit(X_train, y_train)
print(grid.best_score_)
print(grid.best_params_)

0.6939276942344408
{'bootstrap': False, 'max_depth': None, 'max_features': 24, 'min_samples_leaf': 1, 'min_samples_split': 2, 'n_estimators': 1000}

In [72]:
regressor = RandomForestRegressor(random_state=800, n_estimators=1000, max_depth=None, max_features=24, min_samples_split=2, min_samples_leaf=1, bootstrap=False)
regressor.fit(X_train, y_train)
regressor.score(X_test, y_test)


y_pred = regressor.predict(X_test)

rmse = sqrt(mean_squared_error(y_test, y_pred))
rmse

8.439497374723546

**<font color='teal'> Print the intercept value from the linear model. </font>**

Hint: our linear regression model `lm` has an attribute `intercept_` for the intercept

In [70]:
print(lm.intercept_)

-56771266105.624146

**<font color='teal'> The intercept is the mean `AdultWeekend` price for all the resorts given the other characteristics. The addition or subtraction of each of the coefficient values in the regression are numeric adjustments applied to the intercept to provide a particular observation's value for the resulting `AdultWeekend` value. Also, because we took the time to scale our x values in the training data, we can compare each of the coeeficients for the features to determine the feature importances. Print the coefficient values from the linear model and sort in descending order to identify the top ten most important features.</font>** 


Hint: make sure to review the absolute value of the coefficients, because the adjustment may be positive or negative, but what we are looking for is the magnitude of impact on our response variable.

In [96]:
# You might want to make a pandas DataFrame displaying the coefficients for each state like so: 
df_coeff = pd.DataFrame(abs(lm.coef_), X.columns, columns=['Coefficient'])
df_coeff.sort_values('Coefficient', ascending=False)

                    Coefficient
AdultWeekday       9.136828e+00
vertical_drop      3.207299e+00
projectedDaysOpen  3.164054e+00
Unnamed: 0.1       2.504066e+00
Unnamed: 0         2.504066e+00
daysOpenLastYear   2.288448e+00
summit_elev        2.287682e+00
Vermont            2.128713e+00
Colorado           2.073905e+00
Wyoming            2.037880e+00
Massachusetts      1.974720e+00
quad               1.940232e+00
Washington         1.935985e+00
Wisconsin          1.863847e+00
Connecticut        1.771839e+00
SkiableTerrain_ac  1.739295e+00
California         1.670181e+00
LongestRun_mi      1.575303e+00
averageSnowfall    1.560988e+00
triple             1.449864e+00
TerrainParks       1.449352e+00
clusters           1.425123e+00
North Carolina     1.394893e+00
Ohio               1.351077e+00
Tennessee          1.256075e+00
Utah               1.211143e+00
total_chairs       1.205686e+00
Runs               1.138149e+00
New Hampshire      1.127785e+00
double             9.797192e-01
South Dakota       9.496692e-01
Oregon             9.102593e-01
Montana            8.671126e-01
surface            8.223633e-01
Virginia           7.223606e-01
Nevada             7.114058e-01
Illinois           6.502086e-01
Maryland           6.499019e-01
West Virginia      6.470909e-01
Alaska             5.804413e-01
yearsOpen          5.706510e-01
New Mexico         5.617654e-01
NightSkiing_ac     5.546915e-01
Idaho              4.053480e-01
Snow Making_ac     3.836810e-01
Arizona            3.679281e-01
Indiana            2.218776e-01
fastQuads          2.140211e-01
Missouri           2.069401e-01
Maine              1.121298e-01
Rhode Island       1.021271e-01
Pennsylvania       9.866232e-02
Michigan           8.984529e-02
Minnesota          5.048728e-02
Iowa               5.014722e-02
New York           3.318565e-02
fastEight          2.209344e-14
fastSixes          4.385381e-15
trams              2.664535e-15
New Jersey         1.776357e-15

**<font color='teal'>You should see that the top ten important features are different states. However, the state is not something the managers at the Big Mountain Resort can do anything about. Given that we care more about actionable traits associated with ticket pricing, rebuild the model without the state features and compare the results. </font>**

Hint: Try to construct another model using exactly the steps we followed above.

#### Model 2

In [74]:
df1 = pd.read_csv('step3_output.csv').drop('Unnamed: 0', axis=1)
df1.tail()

,Name,state,summit_elev,vertical_drop,trams,fastEight,fastSixes,fastQuads,quad,triple,...,SkiableTerrain_ac,Snow Making_ac,daysOpenLastYear,yearsOpen,averageSnowfall,AdultWeekday,AdultWeekend,projectedDaysOpen,NightSkiing_ac,clusters
170,Sleeping Giant Ski Resort,Wyoming,7428,810,0,0.0,0,0,0,1,...,184.0,18.000000,61.000000,81.0,310.0,42.000000,42.0,77.000000,0.0,1
171,Snow King Resort,Wyoming,7808,1571,0,0.0,0,0,1,1,...,400.0,250.000000,121.000000,80.0,300.0,59.000000,59.0,123.000000,110.0,1
172,Snowy Range Ski & Recreation Area,Wyoming,9663,990,0,0.0,0,0,0,1,...,75.0,30.000000,131.000000,59.0,250.0,49.000000,49.0,131.000000,0.0,1
173,White Pine Ski Area,Wyoming,9500,1100,0,0.0,0,0,0,2,...,370.0,214.109589,115.132143,81.0,150.0,58.000289,49.0,115.132143,0.0,1
174,Big Mountain Resort,Montana,6817,2353,0,0.0,0,3,2,6,...,3000.0,600.000000,123.000000,72.0,333.0,81.000000,81.0,123.000000,600.0,1

In [75]:
X = df1.drop(['Name','AdultWeekend', 'state'], axis=1)

# Declare a response variable, called y, and assign it the AdultWeekend column of the df 
y = df1.AdultWeekend 

# Here we use the StandardScaler() method of the preprocessing package, and then call the fit() method with parameter X 
scaler = preprocessing.StandardScaler().fit(X)

# Declare a variable called X_scaled, and assign it the result of calling the transform() method with parameter X 
X_scaled=scaler.transform(X) 

# Get the 1-dimensional flattened array of our response variable y by calling the ravel() function on y
y = y.ravel()

# Call the train_test_split() function with the first two parameters set to X_scaled and y 
# Declare four variables, X_train, X_test, y_train and y_test separated by commas 
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.25, random_state=1)

lm = linear_model.LinearRegression()
model = lm.fit(X_train,y_train)

# Make a variable called y_pred and assign it the result of calling predict() on our model variable with parameter X_test
y_pred = lm.predict(X_test)

mse1 = mean_absolute_error(y_test, y_pred)
evs1 = explained_variance_score(y_test, y_pred)

print(mse1, evs1)

df1_coeff = pd.DataFrame(abs(lm.coef_), X.columns, columns=['Coefficient'])
df1_coeff.sort_values('Coefficient', ascending=False)

6.529559810359036 0.7999844687071405

                    Coefficient
AdultWeekday       9.682478e+00
summit_elev        2.993743e+00
clusters           2.689063e+00
daysOpenLastYear   2.447120e+00
vertical_drop      2.076205e+00
LongestRun_mi      1.879691e+00
SkiableTerrain_ac  1.726781e+00
quad               1.620611e+00
TerrainParks       1.535135e+00
projectedDaysOpen  1.532606e+00
triple             1.187885e+00
surface            1.063089e+00
averageSnowfall    9.966278e-01
fastQuads          6.904660e-01
Runs               5.699320e-01
total_chairs       4.543805e-01
Snow Making_ac     4.172941e-01
NightSkiing_ac     4.125532e-01
double             3.782159e-01
yearsOpen          3.147906e-01
fastEight          2.664535e-15
fastSixes          6.661338e-16
trams              4.440892e-16

**<font color='teal'> When reviewing our new model coefficients, we see `summit_elev` is now in the number two spot. This is also difficult to change from a management prespective and highly correlated with `base_elev` and `vertical_drop`.  This time, rebuild the model without the state features and without the `summit_elev` and without `base_elev`and compare the results. </font>**

#### Model 3

In [77]:
df2 = pd.read_csv('step3_output.csv').drop(['state', 'summit_elev', 'Unnamed: 0'], axis=1)
df2.head()

,Name,vertical_drop,trams,fastEight,fastSixes,fastQuads,quad,triple,double,surface,...,SkiableTerrain_ac,Snow Making_ac,daysOpenLastYear,yearsOpen,averageSnowfall,AdultWeekday,AdultWeekend,projectedDaysOpen,NightSkiing_ac,clusters
0,Hilltop Ski Area,294,0,0.0,0,0,0,1,0,2,...,30.0,30.000000,150.0,36.0,69.0,30.0,34.000000,152.0,30.0,0
1,Sunrise Park Resort,1800,0,0.0,0,1,2,3,1,0,...,800.0,80.000000,115.0,49.0,250.0,74.0,78.000000,104.0,80.0,1
2,Yosemite Ski & Snowboard Area,600,0,0.0,0,0,0,1,3,1,...,88.0,206.640693,110.0,84.0,300.0,47.0,47.000000,107.0,0.0,1
3,Boreal Mountain Resort,500,0,0.0,0,1,1,3,1,2,...,380.0,200.000000,150.0,54.0,400.0,49.0,64.226929,150.0,200.0,1
4,Dodge Ridge,1600,0,0.0,0,0,1,2,5,4,...,862.0,273.203125,140.0,69.0,350.0,78.0,78.000000,140.0,0.0,1

In [78]:
X = df2.drop(['Name','AdultWeekend'], axis=1)

# Declare a response variable, called y, and assign it the AdultWeekend column of the df 
y = df2.AdultWeekend 

# Here we use the StandardScaler() method of the preprocessing package, and then call the fit() method with parameter X 
scaler = preprocessing.StandardScaler().fit(X)

# Declare a variable called X_scaled, and assign it the result of calling the transform() method with parameter X 
X_scaled=scaler.transform(X) 

# Get the 1-dimensional flattened array of our response variable y by calling the ravel() function on y
y = y.ravel()

# Call the train_test_split() function with the first two parameters set to X_scaled and y 
# Declare four variables, X_train, X_test, y_train and y_test separated by commas 
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.25, random_state=1)

lm = linear_model.LinearRegression()
model = lm.fit(X_train,y_train)

# Make a variable called y_pred and assign it the result of calling predict() on our model variable with parameter X_test
y_pred = lm.predict(X_test)

mse2 = mean_absolute_error(y_test, y_pred)
evs2 = explained_variance_score(y_test, y_pred)

print(mse2, evs2)

df2_coeff = pd.DataFrame(abs(lm.coef_), X.columns, columns=['Coefficient'])
df2_coeff.sort_values('Coefficient', ascending=False)

6.353039725315013 0.8036869203985937

                    Coefficient
AdultWeekday       9.715156e+00
SkiableTerrain_ac  2.606662e+00
daysOpenLastYear   2.281332e+00
LongestRun_mi      2.178759e+00
clusters           2.135436e+00
averageSnowfall    1.956075e+00
projectedDaysOpen  1.493073e+00
TerrainParks       1.487991e+00
vertical_drop      1.441541e+00
quad               1.355126e+00
NightSkiing_ac     1.093695e+00
surface            8.901949e-01
triple             8.228269e-01
Runs               7.931635e-01
Snow Making_ac     7.109783e-01
yearsOpen          4.738392e-01
total_chairs       4.008550e-01
double             3.300497e-01
fastQuads          1.613518e-01
fastEight          1.776357e-15
fastSixes          1.110223e-15
trams              8.881784e-16

In [80]:
model_sel = pd.DataFrame({'Model': ['Model 1.', 'Model 2.', 'Model 3.'], 'Explained Variance': [evs, evs1, evs2], 'Mean Absolute Error': [mae, mse1, mse2], 'Features Dropped': ['base_elev', ['base_elev', 'state'], ['base_elev', 'state', 'summit_elev'] ]})
model_sel

,Model,Explained Variance,Mean Absolute Error,Features Dropped
0,Model 1.,-2.751534e+21,2.257948e+11,base_elev
1,Model 2.,7.999845e-01,6.529560e+00,"[base_elev, state]"
2,Model 3.,8.036869e-01,6.353040e+00,"[base_elev, state, summit_elev]"

## Identify the Final Model

**<font color='teal'> Review the model performances in the table below and choose the best model for proving insights to Big Mountain management about what features are driving ski resort lift ticket prices. Type your choice in the final markdown cell — you will discuss this selection more in the next step of the guided casptone. </font>**

| Model | Explained Variance| Mean Absolute Error|Features Dropped|
| --- | --- | --- | --- |
| Model 1. | 0. |  |-|
| Model 2. | 0.| |'state'|
| Model 3. | 0. | |'state','summit_elev','base_elev'|

Model Selection:

In [ ]:
Model 3